services:
  postgresql:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: ${USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"
